- name: Instalando Squid
  apt: name={{item}} state=installed
  with_items:
       - squid3
       - python-passlib
       - sarg
       - dansguardian

- cron:
    name: Informe de Sarg
    hour: 2
    job: "/usr/local/bin/sarg -x"

- file:
    path: /var/log/dansguardian
    owner: proxy
    group: proxy
    mode: 0755
